import type { PortfolioSectionId } from '../types/portfolio';

export const ROOM_WIDTH = 1360;
export const ROOM_HEIGHT = 884;
export const PLAYER_SPEED = 270;
export const INTERACTION_RADIUS = 78;
export const PLAYER_SPAWN = { x: 742, y: 786 };
export const BOOTH_WIDTH = 188;
export const BOOTH_DEPTH = 60;
export const ROUND_TABLE_SIZE = 88;
export const RECT_TABLE_WIDTH = 84;
export const RECT_TABLE_HEIGHT = 40;

export interface FurnitureDefinition {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color: number;
  stroke: number;
  shape?: 'rectangle' | 'ellipse';
  collides?: boolean;
}

export interface InteractableDefinition {
  id: string;
  sectionId: PortfolioSectionId;
  label: string;
  prompt: string;
  x: number;
  y: number;
  width: number;
  height: number;
  color: number;
}

export interface WallColliderDefinition {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

export const wallColliders: WallColliderDefinition[] = [
  {
    id: 'top-wall',
    x: (ROOM_WIDTH - 156) / 2,
    y: 78,
    width: ROOM_WIDTH - 156,
    height: 156,
  },
  {
    id: 'right-wall',
    x: ROOM_WIDTH - 78,
    y: ROOM_HEIGHT / 2,
    width: 156,
    height: ROOM_HEIGHT,
  },
];

export const furniture: FurnitureDefinition[] = [
  {
    id: 'nook-booth-left',
    x: 30,
    y: 296,
    width: BOOTH_DEPTH,
    height: BOOTH_WIDTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'nook-booth-top',
    x: 154,
    y: 202,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'nook-booth-lower-curve',
    x: 154,
    y: 390,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'nook-round-table',
    x: 154,
    y: 296,
    width: ROUND_TABLE_SIZE,
    height: ROUND_TABLE_SIZE,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
    collides: true,
  },
  {
    id: 'nook-booth-bottom-left',
    x: 30,
    y: 618,
    width: BOOTH_DEPTH,
    height: BOOTH_WIDTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'nook-booth-bottom-top',
    x: 154,
    y: 524,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'nook-booth-bottom-lower-curve',
    x: 154,
    y: 712,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'nook-bottom-round-table',
    x: 154,
    y: 618,
    width: ROUND_TABLE_SIZE,
    height: ROUND_TABLE_SIZE,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
    collides: true,
  },
  {
    id: 'bar-counter-side',
    x: 476,
    y: 144,
    width: 256,
    height: 128,
    color: 0x6b3a1d,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'bar-counter',
    x: 1044,
    y: 144,
    width: 256,
    height: 128,
    color: 0x6b3a1d,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'bar-top-return',
    x: 1044,
    y: 66,
    width: 256,
    height: 42,
    color: 0x6b3a1d,
    stroke: 0xd39c63,
    collides: false,
  },
  {
    id: 'back-bar',
    x: 1148,
    y: 66,
    width: 120,
    height: 42,
    color: 0x43271a,
    stroke: 0x8d6139,
    collides: false,
  },
  {
    id: 'back-bar-shelf-top',
    x: 940,
    y: 66,
    width: 160,
    height: 42,
    color: 0x43271a,
    stroke: 0x8d6139,
    collides: false,
  },
  {
    id: 'bar-stool-1',
    x: 950,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-2',
    x: 998,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-3',
    x: 1046,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-4',
    x: 1094,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-5',
    x: 1142,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-side-1',
    x: 402,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-side-2',
    x: 450,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-side-3',
    x: 498,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'bar-stool-side-4',
    x: 546,
    y: 226,
    width: 34,
    height: 34,
    color: 0x8f6339,
    stroke: 0xd8b074,
    shape: 'ellipse',
  },
  {
    id: 'booth-island-a-top',
    x: 700,
    y: 274,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'booth-island-a-bottom',
    x: 700,
    y: 430,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'booth-island-a-table',
    x: 700,
    y: 352,
    width: ROUND_TABLE_SIZE,
    height: ROUND_TABLE_SIZE,
    color: 0x7a4b28,
    stroke: 0xd8b074,
    shape: 'ellipse',
    collides: true,
  },
  {
    id: 'booth-island-b-top',
    x: 548,
    y: 530,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'booth-island-b-bottom',
    x: 548,
    y: 712,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'booth-island-b-table',
    x: 548,
    y: 621,
    width: ROUND_TABLE_SIZE,
    height: ROUND_TABLE_SIZE,
    color: 0x7a4b28,
    stroke: 0xd8b074,
    shape: 'ellipse',
    collides: true,
  },
  {
    id: 'booth-island-c-top',
    x: 836,
    y: 530,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'booth-island-c-bottom',
    x: 836,
    y: 712,
    width: BOOTH_WIDTH,
    height: BOOTH_DEPTH,
    color: 0x7f2d25,
    stroke: 0xd39c63,
    collides: true,
  },
  {
    id: 'booth-island-c-table',
    x: 836,
    y: 621,
    width: ROUND_TABLE_SIZE,
    height: ROUND_TABLE_SIZE,
    color: 0x7a4b28,
    stroke: 0xd8b074,
    shape: 'ellipse',
    collides: true,
  },
  {
    id: 'rect-table-mid-left-1',
    x: 351,
    y: 532,
    width: RECT_TABLE_WIDTH,
    height: RECT_TABLE_HEIGHT,
    color: 0x7a4b28,
    stroke: 0xd8b074,
    collides: true,
  },
  {
    id: 'rect-table-mid-left-2',
    x: 351,
    y: 714,
    width: RECT_TABLE_WIDTH,
    height: RECT_TABLE_HEIGHT,
    color: 0x7a4b28,
    stroke: 0xd8b074,
    collides: true,
  },
  {
    id: 'rect-table-lower-right-1',
    x: 1084,
    y: 642,
    width: RECT_TABLE_WIDTH,
    height: RECT_TABLE_HEIGHT,
    color: 0x7a4b28,
    stroke: 0xd8b074,
    collides: true,
  },
  {
    id: 'jukebox',
    x: 438,
    y: 326,
    width: 70,
    height: 92,
    color: 0xb45b34,
    stroke: 0xf0c27b,
    collides: true,
  },
  {
    id: 'payphone',
    x: 566,
    y: 798,
    width: 34,
    height: 78,
    color: 0x48505a,
    stroke: 0x9eb2c7,
    collides: true,
  },
  {
    id: 'resume-stand',
    x: 820,
    y: 798,
    width: 118,
    height: 58,
    color: 0x6f4a2d,
    stroke: 0xd8b074,
    collides: false,
  },
];

export const interactables: InteractableDefinition[] = [
  {
    id: 'experience-ledger',
    sectionId: 'experience',
    label: 'Experience',
    prompt: 'Press E to explore',
    x: 690,
    y: 498,
    width: 34,
    height: 34,
    color: 0x77d2ca,
  },
  {
    id: 'jukebox',
    sectionId: 'projects',
    label: 'Jukebox',
    prompt: 'Press E to browse',
    x: 438,
    y: 326,
    width: 40,
    height: 48,
    color: 0xf0c27b,
  },
  {
    id: 'resume-scroll',
    sectionId: 'resume',
    label: 'Resume',
    prompt: 'Press E to inspect',
    x: 820,
    y: 798,
    width: 40,
    height: 32,
    color: 0xf3ead2,
  },
  {
    id: 'contact-phone',
    sectionId: 'contact',
    label: 'Contact',
    prompt: 'Press E to call',
    x: 566,
    y: 798,
    width: 26,
    height: 40,
    color: 0x9eb2c7,
  },
];
